# Configuration for Smart Knowledge Repository

default_target:
  name: Amzur Technologies
  url: https://amzur.com/
  deep_scrape: true

scraping:
  timeout: 30
  retry_attempts: 3

database:
  path: data/profiles.db

ui:
  app_title: Smart Knowledge Repository
  page_icon: 
  layout: wide
